server {
    listen 8088;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream youtube;
        proxy_pass         http://$upstream:8088;
        proxy_set_header   Host localhost:8088;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Connection "";
        proxy_http_version 1.1;

        # 針對 SSE 的重要配置
        proxy_buffering    off;
        proxy_cache        off;
        chunked_transfer_encoding on;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
